services:

    LSB\MessengerBundle\Factory\JobFactory: ~

    lsb_product_factory_job:
        alias: LSB\MessengerBundle\Factory\JobFactory
    LSB\MessengerBundle\Factory\JobFactoryInterface: '@LSB\MessengerBundle\Factory\JobFactory'
